# Generated by Django 5.0.4 on 2024-10-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='expected_response_content',
            field=models.TextField(blank=True, help_text='Expected content in the API response', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='expected_status_code',
            field=models.PositiveIntegerField(blank=True, help_text='Expected HTTP status code', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='http_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='request_body',
            field=models.TextField(blank=True, help_text='Body of the API request', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='request_headers',
            field=models.JSONField(blank=True, help_text='Headers to be sent with the API request', null=True),
        ),
    ]
