# Generated by Django 5.0.4 on 2024-10-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_service_expected_response_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='additional_data',
        ),
    ]
