# Generated by Django 5.0.4 on 2024-10-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_service_additional_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestatus',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
