# Generated by Django 5.1.5 on 2025-02-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_servicestatus_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='project_icons/'),
        ),
    ]
